FORMAT: 1A
HOST: http://localhost:8080

# Première doc API
Description de la première doc API

# Group Authentification

### S'authentifier [POST /auth/login]
- Response 200 (application/json)

### Deconnecter [POST /auth/logout]
- Response 200 (application/json)


# Group Photos

### Poster une image [POST /images/post]
- Response 200 (application/json)

### Get une image en particulier [GET /images/imageId]
- Response 200 (application/json)


# Group Albums

### Get la liste de tous les albums [GET /albums]
- Response 200 (application/json)
