version: '3.1' # minimum version 2
services: # containers. (we can have multiple containers)
    api-renderer:  # the service name you want (not the container name). It si also the DNS name inside the network
        build:
            context: .
            dockerfile: 'APIRenderer.dockerfile'
        working_dir: /root/api_documentation
        volumes:
            - ../doc/api:/root/api_documentation
        entrypoint: bash -c "while true; do sleep 500; done"
    api-server:
        build:
            context: api_server
            dockerfile: 'php_mysql_server.dockerfile'
        ports:
            - "8080:80"
        volumes:
            - ../api/src:/var/www/html
            - ../api/databases:/var/databases
        entrypoint: bash /api_server_entrypoint.sh
